config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users

  resources :posts do
    resources :comments, shallow: true, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: nil

  validates :name, length: { in: 2..100 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', inverse_of: 'posts'
  belongs_to :category
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, length: { in: 5..255 }
  validates :body, length: { in: 200..4000 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_ancestry

  validates :content, length: { in: 2..255 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user

  validates :user_id, uniqueness: {
    scope: :post_id, message: I18n.t('activerecord.errors.models.post_like.already_liked')
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: nil, inverse_of: 'creator'
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale

  def default_url_options
    { locale: I18n.locale || I18n.default_locale }
  end

  private

  def switch_locale(&)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    @comment = build_comment(post)

    if @comment.save
      redirect_to post_path(post), notice: t('comments.created')
    else
      redirect_to post_path(post), alert: @comment.errors.full_messages.join('. ')
    end
  end

  def destroy
    comment = PostComment.find(params[:id])
    return if comment.user != current_user

    post = comment.post
    comment.destroy

    redirect_to post_path(post), notice: t('comments.destroyed')
  end

  private

  def comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end

  def build_comment(post)
    post.comments.build(comment_params.merge(user: current_user))
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    post.likes.find_or_create_by(user: current_user)
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    post.likes.find_by(user: current_user)&.destroy

    redirect_to post_path(post)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_post, only: %i[edit update]
  before_action :set_post_with_comments, only: %i[show destroy]

  def index
    @posts = Post.includes(:category, :creator).order(created_at: :desc)
  end

  def show; end

  def new
    @post = current_user.posts.build
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_url(@post), notice: t('posts.actions.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: t('posts.actions.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!

    redirect_to posts_url, notice: t('posts.actions.deleted')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_post_with_comments
    @post = Post
            .joins(:category, :creator)
            .includes(:likes, comments: :user)
            .find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def render_post_likes_icon(post)
    if current_user
      icon_with_a_link(post)
    else
      content_tag(:i, '', class: 'i bi bi-hand-thumbs-up text-dark')
    end
  end

  private

  def icon_with_a_link(post)
    like = current_post_like(post)
    if like
      link_to post_like_path(post, like), data: { turbo_method: :delete }, class: 'text-dark' do
        content_tag(:i, '', class: 'i bi bi-hand-thumbs-up-fill')
      end
    else
      link_to post_likes_path(post), data: { turbo_method: :post }, class: 'text-dark' do
        content_tag(:i, '', class: 'i bi bi-hand-thumbs-up')
      end
    end
  end

  def current_post_like(post)
    return unless current_user

    post.likes.find { |like| like.user_id == current_user.id }
  end
end

app/views/comments/_comment.html.slim
.card.card-body.py-0.my-3
  .card-header.border-0
    small
      =< comment.user.email
      | &nbsp; &nbsp; &nbsp;
      =< l(comment.created_at, format: :short)

  .card-text
    = comment.content
    | &nbsp;
    - if comment.user == current_user
      = link_to t('comments.delete'),
        comment_path(comment),
        data: { turbo_method: :delete, turbo_confirm: t('actions.delete.confirm') }

  - if current_user
    .card-footer.border-0
      a.fs-6.text-decoration-underline.text-lowercase.collapsed [
        data-bs-toggle='collapse'
        href='#' type='button'
        data-bs-target="#response_comment-#{comment.id}"
        aria-expanded='false'
        aria-controls="response_comment-#{comment.id}"
      ]
        = t('comments.answer')

      div class='collapse' id="response_comment-#{comment.id}"
        = render '/comments/form',
          comment: @post.comments.build(parent_id: comment.id),
          url: post_comments_path(@post)

  - if comment.has_children?
    = render partial: '/comments/comment',
      collection: comment.children.order(created_at: :desc).reject(&:new_record?)

app/views/comments/_form.html.slim
= simple_form_for(comment, url:) do |f|
  = f.error_notification
  - if f.object.errors[:base].present?
    = f.error_notification message: f.object.errors[:base].to_sentence

  .form-inputs
    = f.input :content, input_html: { maxlength: 255 }
    = f.hidden_field :parent_id

  .form-actions.mb-3
    = f.button :submit, class: 'btn btn-primary'

app/views/comments/edit.html.slim
h1 Comments#edit
p Find me in app/views/comments/edit.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsProject64
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body

    header
      = render 'layouts/application/nav'

    main.mt-5.pt-3
      .container
        = render 'layouts/application/flash'
        = yield

  footer
    .container.footer.sticky-bottom.py-3.bg-light.text-muted
      = t('footer.powered')
      br
      = t('footer.contact_us')

app/views/layouts/application/_flash.html.slim
- flash.each do |name, msg|
  - if name == 'notice'
    .alert.alert-info role='alert'
      = msg
  - if name == 'alert'
    .alert.alert-danger role='alert'
      = msg

app/views/layouts/application/_nav.html.slim
nav class='container navbar navbar-expand-md d-flex py-2 border-bottom\
  fixed-top justify-content-between bg-white'

  a.navbar-brand href='/'
    = image_tag('hexlet_logo.jpg', size: '30x30', alt: 'Hexlet')

  button.navbar-toggler [
    type='button'
    data-bs-toggle='collapse'
    data-bs-target='#navbarSupportedContent'
    aria-controls='navbarSupportedContent'
    aria-expanded='false'
    aria-label='Toggle navigation'
  ]
    span.navbar-toggler-icon
  .collapse.navbar-collapse.justify-content-end id='navbarSupportedContent'
    .d-flex
      ul.nav

        - I18n.available_locales.each do |locale|
          li
            - unless I18n.locale == locale
              = link_to t(locale, scope: 'locales'), url_for(locale:), class: 'btn'

        - if user_signed_in?
          li.nav-link.disabled
            = current_user.email
          li.nav-item
            = link_to t('posts.new'), new_post_path, class: 'btn'
          li.nav-item
            = link_to t('auth.log_out'),
              destroy_user_session_path,
              data: { turbo_method: :delete },
              class: 'btn'
        - else
          li.nav-item
            = link_to t('auth.log_in'), new_user_session_path, class: 'btn'
            = link_to t('auth.sign_up'), new_user_registration_path, class: 'btn'

app/views/posts/_form.html.slim
= simple_form_for(post) do |f|
  = f.error_notification
  - if f.object.errors[:base].present?
    = f.error_notification message: f.object.errors[:base].to_sentence

  .form-inputs
    = f.input :title,
      hint: "5-255 #{t('posts.symbols')}",
      input_html: { maxlength: 255 }
    = f.input :body,
      hint: "200-4000 #{t('posts.symbols')}",
      input_html: { maxlength: 4000 }
    = f.association :category

  .form-actions.mb-3
    = f.button :submit, class: 'btn btn-primary'

app/views/posts/edit.html.slim
.d-flex.py-2
  .me-2 = link_to t('posts.all'), posts_path
  .ms-2 = link_to t('actions.back'), :back
h1 = t('posts.actions.editing')

= render 'form', post: @post

app/views/posts/index.html.slim
h1 = t('views.posts.index.title')

#posts
- @posts.each do |post|
  .card.my-3
    .card-body
      p.card-subtitle.text-body-secondary
        = post.category.name
      h5.card-title
        = link_to post.title, post, class: 'link-dark text-decoration-none'

      p.card-text
        = truncate post.body, length: 300
      small
        = t('posts.liked')
        | :
        =< post.post_likes_count
        | &nbsp; &nbsp; &nbsp;
        = t('posts.published')
        | :
        =< l(post.created_at, format: :short)
        | &nbsp; &nbsp; &nbsp;
        = t('posts.by')
        | :
        =< post.creator.email

app/views/posts/new.html.slim
.d-flex.py-2
  .me-2 = link_to t('posts.all'), posts_path
  .ms-2 = link_to t('actions.back'), :back

h1 = t('posts.new')

== render 'form', post: @post

app/views/posts/show.html.slim
.container.my-4
  => link_to t('posts.posts'), posts_path
  | /
  =< @post.category.name

  div id="#{dom_id @post}"
    .small.mt-3
        = t('posts.published')
        | :
        =< l(@post.created_at, format: :short)
        | &nbsp; &nbsp; &nbsp;
        = t('posts.by')
        | :
        =< @post.creator.email

    h1.mb-3 = @post.title

    p = @post.body

    = @post.post_likes_count
    = render_post_likes_icon(@post)

  - if current_user && @post.creator == current_user
    .btn-group.btn-group-sm.mt-3 role='group' aria-label='Post button group'
      = button_to t('posts.actions.update'),
        edit_post_path(@post),
        method: :get,
        class: 'btn btn-primary'

      p = link_to t('posts.actions.delete'),
          post_path(@post),
          data: { turbo_method: :delete, turbo_confirm: t('actions.delete.confirm') },
          class: 'btn btn-outline-danger'

  - if current_user
    = render '/comments/form', comment: @post.comments.build, url: post_comments_path(@post)

  = render partial: '/comments/comment',
    collection: @post.comments.where(ancestry: nil).order(created_at: :desc).to_a